package:
  name: wasmcloud
  version: 1.0.1
  epoch: 0
  description: "wasmCloud allows for simple, secure, distributed application development using WebAssembly components and capability providers."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wasmCloud/wasmCloud
      tag: v${{package.version}}
      expected-commit: eb9e4a3165bd6a94117642deb3a90c8d028706d7

  - name: Configure and build
    runs: |
      cargo build --release --bin wasmcloud
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasmcloud ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: wasmCloud/wasmCloud
    strip-prefix: v

test:
  pipeline:
    - name: Verify wasmcloud installation
      runs: |
        wasmcloud --version || exit 1